version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./Backend:/app
    depends_on:
      - mysql
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./Frontend:/app
    ports:
      - "3000:3000"
    restart: always


  mysql:
    image: mysql:8.0
    container_name: fyp_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "3307:3306"
    volumes:
      - ./init_schema.sql:/docker-entrypoint-initdb.d/init_schema.sql
    restart: always

volumes:
  mysql_data:
